# GPIO
CONFIG_GPIO=y

# Bluetooth HCI raw mode
CONFIG_BT=y
CONFIG_BT_HCI_RAW=y
CONFIG_BT_HCI_RAW_H4=y
CONFIG_BT_HCI_RAW_H4_ENABLE=y

# Buffer sizes
CONFIG_BT_BUF_ACL_RX_SIZE=255
CONFIG_BT_BUF_CMD_TX_SIZE=255
CONFIG_BT_BUF_EVT_DISCARDABLE_SIZE=255

# BT host options (controller runs on cpunet, not cpuapp)
CONFIG_BT_MAX_CONN=16

CONFIG_REBOOT=y
