# Project Information
g_PROJECT_NAME="alfie"
g_NORDIC_TOOLCHAIN_VERSION=v3.1.1
g_DEFAULT_BUILD_TARGET="app"
g_DEFAULT_BUILD_BOARD="dectcomm/nrf9151/ns"

g_BRIDGE_BUILD_TARGET="ble_bridge"
g_BRIDGE_BUILD_BOARD="dectcomm/nrf5340/cpuapp/ns"
g_BRIDGE_BUILD_DIRECTORY="build_bridge"
